server:
  port: 8080
spring:
  application:
    name: api-gateway-service
#  main:
#    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/ecommerce
  cloud:
    gateway:
#      default-filters:
#        - AddAuthenticatedUserInHeaderFilter
#        - LoggingFilter
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
          # NOT => Filter'lar burada tanımlandığı sırayla çalışırlar !!! AbstractGatewayFilterFactory ile oluşturulan filter'lara Ordered işlemez. Buradaki sıra önemli
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/v1/category/**
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - LoggingFilter
#             - AddAuthenticatedUserInHeaderFilter
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/api/v1/storage/**
          filters:
            - LoggingFilter
            - AddAuthenticatedUserInHeaderFilter
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
