# server
huseyinari.ecommerce.base-url=http://localhost:8080
huseyinari.ecommerce.storage-object-content-url=${huseyinari.ecommerce.base-url}/api/v1/storage/content

# Kafka topic isimleri
huseyinari.ecommerce.kafka.topics.create-opening-product-stock=CREATE_OPENING_PRODUCT_STOCK
huseyinari.ecommerce.kafka.topics.create-opening-product-stock-failed=CREATE_OPENING_PRODUCT_STOCK_FAILED
huseyinari.ecommerce.kafka.topics.create-opening-product-stock-success=CREATE_OPENING_PRODUCT_STOCK_SUCCESS

# S3
huseyinari.ecommerce.s3.buckets.product-images-bucket-name=ecommerce-product-images-bucket