huseyinari.ecommerce.metadata.product-service-url=localhost:8091
huseyinari.ecommerce.metadata.inventory-service-url=localhost:8092

# Kafka topic isimleri
huseyinari.ecommerce.kafka.topics.create-opening-product-stock=CREATE_OPENING_PRODUCT_STOCK
huseyinari.ecommerce.kafka.topics.create-opening-product-stock-failed=CREATE_OPENING_PRODUCT_STOCK_FAILED
huseyinari.ecommerce.kafka.topics.create-opening-product-stock-success=CREATE_OPENING_PRODUCT_STOCK_SUCCESS
