# actuator
# management.endpoints.web.exposure.include:*
management.endpoints.web.exposure.include=prometheus,metrics
management.metrics.export.prometheus.enabled=true

# swagger-ui
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/auth/swagger/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/auth/swagger
springdoc.swagger-ui.url=/auth/swagger/v3/api-docs