huseyinari.ecommerce.aws.s3.accessKeyId=AKIATEGP4KBUEBMIKHSV
huseyinari.ecommerce.aws.s3.secretKey=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
huseyinari.ecommerce.aws.s3.bucketName=huseyinari-ecommerce-demo
huseyinari.ecommerce.aws.s3.region=eu-north-1