server:
  port: 8080
spring:
  application:
    name: api-gateway-service
#  main:
#    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/ecommerce
  cloud:
    gateway:
#      default-filters:
#        - AddAuthenticatedUserInHeaderFilter
#        - LoggingFilter
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**,/api/v1/product/**,/api/v1/product-image/**,/api/v1/product-attribute/**
          # NOT => Filter'lar burada tanımlandığı sırayla çalışırlar !!! AbstractGatewayFilterFactory ile oluşturulan filter'lara Ordered işlemez. Buradaki sıra önemli
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**,/api/v1/order/**
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**,/api/v1/inventory/**
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/category/**,/api/v1/category/**,/api/v1/carousel-item/**
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/api/v1/auth/**
          filters:
            - LoggingFilter
#             - AddAuthenticatedUserInHeaderFilter
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storage/**,/api/v1/storage/**,/public/storage/**
          filters:
            - AddAuthenticatedUserInHeaderFilter
            - LoggingFilter
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: product-service
        url: /product/swagger/v3/api-docs
      - name: category-service
        url: /category/swagger/v3/api-docs
      - name: inventory-service
        url: /inventory/swagger/v3/api-docs
      - name: order-service
        url: /order/swagger/v3/api-docs
      - name: storage-service
        url: /storage/swagger/v3/api-docs
      - name: auth-service
        url: /auth/swagger/v3/api-docs