# Server
huseyinari.ecommerce.base-url=http://localhost:8080
huseyinari.ecommerce.storage-object-content-url=${huseyinari.ecommerce.base-url}/api/v1/storage/content

# Storage
huseyinari.ecommerce.local-storage-file-path=/Users/sinha/Desktop/ecommerce/local-storage
huseyinari.ecommerce.max-upload-file-size=20971520

# Kafka
huseyinari.ecommerce.kafka.topics.create-opening-product-stock=CREATE_OPENING_PRODUCT_STOCK
huseyinari.ecommerce.kafka.topics.create-opening-product-stock-failed=CREATE_OPENING_PRODUCT_STOCK_FAILED
huseyinari.ecommerce.kafka.topics.create-opening-product-stock-success=CREATE_OPENING_PRODUCT_STOCK_SUCCESS


# AWS
huseyinari.ecommerce.aws.s3.accessKeyId=xxx
huseyinari.ecommerce.aws.s3.secretKey=xxx
huseyinari.ecommerce.aws.s3.bucketName=xxx
huseyinari.ecommerce.aws.s3.region=eu-north-1
huseyinari.ecommerce.aws.s3.product-images-bucket-name=ecommerce-product-images-bucket
huseyinari.ecommerce.aws.s3.category-images-bucket-name=ecommerce-category-images


# Keycloak
huseyinari.ecommerce.keycloak.serverUrl=http://localhost:8088
huseyinari.ecommerce.keycloak.realm=ecommerce
huseyinari.ecommerce.keycloak.clientId=ecommerce-client
huseyinari.ecommerce.keycloak.clientSecret=xxx
huseyinari.ecommerce.keycloak.adminUsername=xxx
huseyinari.ecommerce.keycloak.adminPassword=xxx