# ------------- Properties Dosyalarını Local Klasörden Alacak Yapılandırma ------------- (-Dspring.profiles.active=native OLARAK BAŞLATILMALI !)
spring.cloud.config.server.native.search-locations=file:///Users/sinha/Desktop/ecommerce/config_files

# actuator
# management.endpoints.web.exposure.include:*
management.endpoints.web.exposure.include=prometheus,metrics
management.metrics.export.prometheus.enabled=true