spring.application.name=config-server
server.port=8888

# ------------- Properties Dosyalarını Uzak Repo'dan Alacak Yapılandırma -------------
#spring.cloud.config.server.git.uri=https://github.com/huseyinari/spring-boot-ecommerce-config-server.git
#spring.cloud.config.server.git.username=huseyinari
#spring.cloud.config.server.git.password=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
#spring.cloud.config.server.git.default-label=master