spring.application.name=config-server
server.port=8888

# Repository Location in Github
spring.cloud.config.server.git.uri=https://github.com/huseyinari/spring-cloud-config-server-example.git
# Github username
spring.cloud.config.server.git.username=huseyinari
# Github Password (Token)
spring.cloud.config.server.git.password=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
# Github default branch
spring.cloud.config.server.git.default-label=master