server:
  port: 8080
spring:
  application:
    name: api-gateway-service
#  main:
#    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/ecommerce
  cloud:
    gateway:
#      default-filters:
#        - TokenRelay=
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka